 steps:
 # build the container image name clock_angle
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/clock-angle:$COMMIT_SHA', '.']
 # push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/clock-angle:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/cloud-builders/gcloud'
   args:
   - 'run'
   - 'deploy'
   - 'clock-angle'
   - '--image'
   - 'gcr.io/$PROJECT_ID/clock-angle:$COMMIT_SHA'
   - '--region'
   - 'us-east1'
   - '--platform'
   - 'managed'
   - '--allow-unauthenticated'
   
 images:
 - 'gcr.io/$PROJECT_ID/clock-angle:$COMMIT_SHA'
 

    